version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres_super_db 
    ports:
      - '5432:5432'
    volumes: 
      - postgres_vol:/var/lib/postgresql/data
      - ./customers.sql:/docker-entrypoint-initdb.d/customers.sql
  python_app:
    build: ./python_stuff/
volumes:
  postgres_vol:
    driver: local