version: "3.8"
services:
  db:
    image: postgres
    # container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      # this is causing problmes for some reason
      # - POSTGRES_DB=postgres_super_db 
    ports:
      - '5432:5432'
    volumes: 
      - postgres_vol:/var/lib/postgresql/data
      - ./quotes.sql:/docker-entrypoint-initdb.d/quotes.sql
volumes:
  postgres_vol:
    driver: local