version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres_super_db 
    ports:
      - '5432:5432'
    volumes: 
      - postgres_vol:/var/lib/postgresql/data
      # - ./quotes.sql:/docker-entrypoint-initdb.d/quotes.sql
      # - ./dummy_db.sql:/docker-entrypoint-initdb.d/dummy_db.sql
      - ./world_db:/docker-entrypoint-initdb.d
  python_app:
    build: ./app_python/
volumes:
  postgres_vol:
    driver: local